materials = {
    'aluminum': ['aluminum', 'aluminium', 'alum'],
    'asphalt': ['asphalt', 'bitumen', 'tar'],
    'brass': ['brass', 'bronz', 'copper-zinc'],
    'bronze': ['bronze', 'brass', 'copper-tin'],
     'boron': ['boron'],
    'beryllium': ['beryllium'],
    'bismuth': ['bismuth'],
    'barite': ['barite'],
    'bitumen': ['bitumen', 'asphalt', 'tar'],
    'bauxite': ['bauxite'],
    'basalt': ['basalt'],
    'bakelite': ['bakelite'],
    'balsa wood': ['balsa-wood'],
    'bamboo': ['bamboo'],
    'beech wood': ['beech-wood'],
    'birch wood': ['birch-wood'],
    'bloodwood': ['bloodwood'],
    'carbon fiber': ['carbon-fiber', 'carbon-fibre', 'graphite-fiber'],
    'cast iron': ['cast-iron', 'gray-iron', 'white_iron'],
    'calcium': ['calcium'],
    'carbon': ['carbon'],
    'cement': ['cement'],
    'ceramics': ['ceramics'],
    'chromium': ['chromium'],
    'cobalt': ['cobalt'],
    'copper': ['copper'],
    'cellulose': ['cellulose'],
    'cork': ['cork'],
    'cotton': ['cotton'],
    'concrete': ['concrete'],
    'corundum': ['corundum'],
    'cinnabar': ['cinnabar'],
    'cesium': ['cesium'],
    'ceramic': ['ceramic', 'pottery', 'porcelain'],
    'chrome': ['chrome', 'chromium', 'chromed-metal'],
    'copper': ['copper', 'copper-alloy', 'brass', 'bronze'],
    'cotton': ['cotton', 'cotton-fiber', 'cotton-wool'],
    'diamond': ['diamond', 'gemstone', 'jewel'],
    'dolomite': ['dolomite'],
    'dysprosium': ['dysprosium'],
    'duralumin': ['duralumin'],
    'epoxy': ['epoxy', 'resin', 'adhesive'],
     'ebonite': ['ebonite'],
    'elastic': ['elastic'],
    'electrum': ['electrum'],
    'epoxy': ['epoxy'],
    'europium': ['europium'],
    'emery': ['emery'],
    'emerald': ['emerald'],
    'enamel': ['enamel'],
    'erbium': ['erbium'],
    'fiberglass': ['fiberglass', 'glass-fiber'],
    'fabric': ['fabric', 'textile', 'cloth', 'material'],
'ferrite': ['ferrite', 'iron-oxide', 'Fe3O4', 'magnetite'],
'fiber': ['fiber', 'fibre', 'filament'],
'fiberglass': ['fiberglass', 'fibreglass', 'GRP', 'glass-reinforced plastic'],
'foil': ['foil', 'metal-leaf', 'thin-sheet-metal'],
'formica': ['formica', 'laminated-plastic', 'melamine'],
'frp': ['frp', 'fiber-reinforced-plastic', 'fiber-reinforced-polymer'],
    'foam': ['foam', 'sponge', 'puff'],
    'glass': ['glass', 'crystal', 'mirror'],
    'gold': ['gold', 'yellow-metal', 'au'],
    'granite': ['granite', 'stone', 'rock'],
    'graphene': ['graphene', 'carbon-sheet', 'nanotube'],
    
    'hardwood': ['hardwood', 'wood', 'timber'],
        'halite': ['halite', 'rock-salt'],
    'hardboard': ['hardboard', 'high-density fiberboard'],
    'hardwood': ['hardwood', 'solid-wood'],
    'hematite': ['hematite', 'iron-ore'],
    'hemp': ['hemp'],
    'hickory': ['hickory'],
    'honeycomb': ['honeycomb'],
    'hornblende': ['hornblende'],
    'humus': ['humus'],
    
    'iron': ['iron', 'iron-ore', 'steel'],
    'jade': ['jade', 'green-stone', 'gem'],
    'kevlar': ['kevlar', 'aramid-fiber', 'bulletproof material'],
    'leather': ['leather', 'hide', 'skin'],
    'limestone': ['limestone', 'calcium-carbonate', 'chalk'],
    'linen': ['linen', 'flax', 'cloth'],
    'marble': ['marble', 'stone', 'rock'],
    'nickel': ['nickel', 'nickel-alloy', 'stainless-steel'],
    'nylon': ['nylon', 'polyamide', 'synthetic-fiber'],
    'oak': ['oak', 'hardwood', 'wood'],
    'paper': ['paper', 'cardboard', 'pulp'],
    'pearls': ['pearls', 'nacre', 'mother-of-pearl'],
    'platinum': ['platinum', 'white metal', 'pt'],
    'polycarbonate': ['polycarbonate', 'pc', 'lexan'],
    'polyester': ['polyester', 'pet', 'plastic'],
    'polypropylene': ['polypropylene', 'pp', 'plastic'],
    'polystyrene': ['polystyrene', 'ps', 'plastic'],
    'polyurethane': ['polyurethane', 'pu', 'plastic'],
    'pvc': ['pvc', 'polyvinyl chloride', 'plastic'],
    'quartz': ['quartz', 'silica', 'crystal'],
    'rubber': ['rubber', 'latex', 'elastic material'],
    'sapphire': ['sapphire', 'blue-stone', 'gem'],
    'satin': ['satin', 'silk', 'cloth'],
'steatite': ['steatite', 'soapstone', 'talc-rock'],
'steel': ['steel', 'carbon-steel', 'stainless-steel'],
'sterling silver': ['sterling-silver', '925silver', 'silver-alloy'],
'titanium': ['titanium', 'Ti', 'titanium-alloy'],
'tungsten': ['tungsten', 'W', 'tungsten alloy'],
'urea formaldehyde': ['urea formaldehyde', 'UF', 'resin'],
'zinc': ['zinc', 'zinc-alloy', 'galvanized-metal'],
'zirconia': ['zirconia', 'zirconium-oxide', 'ceramic'],
'wool': ['wool', 'yarn'],
'steatite': ['steatite', 'soapstone', 'talc-rock'],
'boron carbide': ['boron-carbide', 'B4C', 'ceramic'],
'bristle': ['bristle', 'hair', 'natural-fiber'],
'carbon steel': ['carbon-steel', 'iron-carbon-alloy', 'steel'],
'concrete': ['concrete', 'cement', 'mortar'],
'corduroy': ['corduroy', 'cotton fabric', 'ribbed-fabric'],
'electrum': ['electrum', 'gold-silver-alloy', 'precious-metal'],
'gypsum': ['gypsum', 'plaster', 'drywall'],
'hemp': ['hemp', 'hemp-fiber', 'cannabis'],
'jute': ['jute', 'jute fiber', 'burlap'],
'kapok': ['kapok', 'kapok-fiber', 'silk-cotton'],
'linoleum': ['linoleum', 'flooring', 'marmoleum'],
'neoprene': ['neoprene', 'synthetic-rubber', 'chloroprene-rubber'],
'pewter': ['pewter', 'tin-alloy', 'silver-gray-metal'],
'quilt': ['quilt', 'blanket', 'comforter'],
'shellac': ['shellac', 'resin', 'lac'],
'silicon': ['silicon', 'Si', 'semiconductor-material'],
'sisal': ['sisal', 'sisal-fiber', 'rope'],
'stone wool': ['stone-wool', 'mineral-wool', 'rock-wool'],
'terrazzo': ['terrazzo', 'flooring', 'mosaic'],
'thatch': ['thatch', 'straw', 'grass'],
'velvet': ['velvet', 'silk-velvet', 'fabric'],
'viscose': ['viscose', 'rayon', 'artificial-silk'],
'wicker': ['wicker', 'rattan', 'cane'],
'wire': ['wire', 'cable', 'metal-thread'],

    'Titanium': ['titanium'],
    'Tungsten': ['tungsten'],
    'Uranium': ['uranium'],
    'Vanadium': ['vanadium'],
    'Waste': ['waste'],
    'Water': ['water'],
    
     'wood': ['wood', 'timber', 'lumber', 'plywood'],
    'steel': ['steel', 'iron', 'metal', 'alloy'],
    'aluminum': ['aluminum', 'aluminium', 'metal', 'lightweight-metal','alu'],
    'plastic': ['plastic', 'polymer', 'synthetic', 'resin'],
    'glass': ['glass', 'crystal', 'transparent-material', 'brittle-material'],
    'concrete': ['concrete', 'cement', 'building-material', 'hard-substance'],
    'copper': ['copper', 'metal', 'red-metal', 'conducting-material'],
    'rubber': ['rubber', 'elastic-material', 'synthetic-material', 'tire-material'],
    'gold': ['gold', 'precious-metal', 'valuable-material', 'shiny-metal'],
    'silver': ['silver', 'precious-metal', 'shiny-metal', 'jewelry-material'],
    'iron': ['iron', 'metal', 'rusting-material', 'magnetic-material'],
    'titanium': ['titanium', 'metal', 'lightweight-metal', 'corrosion-resistant-material'],
    'brass': ['brass', 'metal', 'yellow-metal', 'decorative-material'],
    'zinc': ['zinc', 'metal', 'corrosion-resistant-material', 'galvanized-material'],
    'nickel': ['nickel', 'metal', 'silver-colored-material', 'corrosion-resistant-material'],
    'bronze': ['bronze', 'metal', 'alloy', 'brownish-material'],
    'ceramic': ['ceramic', 'pottery', 'clay-material', 'brittle-material'],
    'paper': ['paper', 'cardboard', 'material', 'recyclable-material'],
    'silk': ['silk', 'natural-material', 'luxurious-material', 'smooth-fabric'],
    'cotton': ['cotton', 'natural-material', 'soft-material', 'absorbent-material'],
    'leather': ['leather', 'animal-skin', 'durable-material', 'luxurious-material'],
    'wool': ['wool', 'natural-material', 'warm-material', 'soft-fabric'],
    'linen': ['linen', 'natural-material', 'cool-material', 'breathable-fabric'],
    'polyester': ['polyester', 'synthetic-material', 'durable-material', 'wrinkle-resistant-material'],
    'nylon': ['nylon', 'synthetic-material', 'tough-material', 'stretchy-material'],
    'rayon': ['rayon', 'synthetic-material', 'soft-material', 'absorbent-material'],
    'acrylic': ['acrylic', 'synthetic-material', 'soft-material', 'warm-material'],
    'polypropylene': ['polypropylene', 'synthetic-material', 'tough-material', 'chemical-resistant-material'],
    'polyethylene': ['polyethylene', 'synthetic-material', 'plastic-material', 'versatile-material'],
    'polycarbonate': ['polycarbonate', 'synthetic-material', 'durable-material', 'transparent-material'],
    'carbon fiber': ['carbon-fiber', 'composite-material', 'lightweight-material', 'strong-material'],
    'kevlar': ['kevlar', 'composite-material', 'bulletproof-material', 'tough-material'],
    'graphene': ['graphene', 'nanomaterial', 'strong-material', 'lightweight-material'],
    'wicker': ['wicker', 'rattan', 'cane', 'bamboo'],
'wire': ['wire', 'cable', 'metal thread', 'electrical conductor'],
'wood': ['wood', 'timber', 'lumber', 'plywood', 'balsa'],
'steel': ['steel', 'iron', 'metal', 'alloy', 'stainless steel'],
'acrylic': ['acrylic', 'plexiglass'],
    'asbestos': ['asbestos'],
    'asphalt': ['asphalt', 'bitumen', 'tar'],
    'ash': ['ash'],
    'ammonia': ['ammonia'],
    'amber': ['amber'],
    'antimony': ['antimony'],
    'alabaster': ['alabaster'],
    'aerogel': ['aerogel'],
    'aramid': ['aramid', 'Kevlar'],
    'apatite': ['apatite'],
    'agate': ['agate'],
    'azurite': ['azurite'],
    'actinolite': ['actinolite'],
'plastic': ['plastic', 'polymer', 'synthetic', 'resin', 'thermoplastic'],
'glass': ['glass', 'crystal', 'transparent material', 'brittle material', 'borosilicate glass'],
'concrete': ['concrete', 'cement', 'building material', 'hard substance', 'precast concrete'],
'copper': ['copper', 'metal', 'red metal', 'conducting material', 'copper wire'],
'rubber': ['rubber', 'elastic material', 'synthetic material', 'tire material', 'latex'],
'gold': ['gold', 'precious metal', 'valuable material', 'shiny metal', 'rose gold'],
'silver': ['silver', 'precious metal', 'shiny metal', 'jewelry material', 'sterling silver'],
'iron': ['iron', 'metal', 'rusting material', 'magnetic material', 'cast iron'],
'titanium': ['titanium', 'metal', 'lightweight metal', 'corrosion-resistant material', 'titanium dioxide'],
'brass': ['brass', 'metal', 'yellow metal', 'decorative material', 'brass instruments'],
'zinc': ['zinc', 'metal', 'corrosion-resistant material', 'galvanized material', 'zinc alloy'],
'nickel': ['nickel', 'metal', 'silver-colored material', 'corrosion-resistant material', 'nickel plating'],
'bronze': ['bronze', 'metal', 'alloy', 'brownish material', 'bronze sculpture'],
'ceramic': ['ceramic', 'pottery', 'clay material', 'brittle material', 'porcelain'],
'paper': ['paper', 'cardboard', 'material', 'recyclable material', 'tissue paper'],
'silk': ['silk', 'natural material', 'luxurious material', 'smooth fabric', 'satin'],
'cotton': ['cotton', 'natural material', 'soft material', 'absorbent material', 'organic cotton'],
'leather': ['leather', 'animal skin', 'durable material', 'luxurious material', 'suede'],
'wool': ['wool', 'natural material', 'warm material', 'soft fabric', 'cashmere'],
'linen': ['linen', 'natural material', 'cool material', 'breathable fabric', 'flax'],
'polyester': ['polyester', 'synthetic material', 'durable material', 'wrinkle-resistant material', 'polyester blend'],
'nylon': ['nylon', 'synthetic material', 'tough material', 'stretchy material', 'nylon mesh'],
'rayon': ['rayon', 'synthetic material', 'soft material', 'absorbent material', 'viscose rayon'],
'acrylic': ['acrylic', 'synthetic',  'warm-material', 'acrylic-yarn']

}
import re
def find_materials(text):
    mat=[]
    words = re.findall(r'\b\w+\b', text)
    for word in words:
        flag="null"
        for material, aliases in materials.items():
            for alias in aliases:
                if alias==word.lower():               
                    mat.append(material)
                    flag="green"
                    break
            if flag=="green":
                break
                
        
    return mat